apiVersion: v1
kind: Secret
metadata:
  name: blog-frontend-secret
type: Opaque
data:
  # Base64 encoded values - zmień na swoje wartości
  next-public-api-url: <base64-encoded-api-url>
  next-public-app-url: <base64-encoded-app-url>
